{
 "title": "Bonus",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "my_mem_total", "legendFormat": "__auto" },
    { "expr": "my_mem_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_cpu{instance=\"localhost:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "my_disk_total", "legendFormat": "__auto" },
    { "expr": "my_disk_used", "legendFormat": "__auto" }
   ]
  }
 ]
}