{
 "title": "My dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "- available RAM" }
   ]
  },
  {
   "title": "Free space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "- available space"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\", mountpoint=\"/\"}",
     "legendFormat": "- total spase"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (irate(node_cpu_seconds_total{cpu=\"0\", job=\"node\", mode=\"idle\"}[5m])) * 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input/output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"vda\"}[5m])",
     "legendFormat": "- input"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"localhost:9100\", device=\"vda\"}[5m])",
     "legendFormat": "- output"
    }
   ]
  }
 ]
}